name: Caching Demo Workfloe
on: workflow_dispatch
jobs:
  build-job:
    name: Caching Demo to understand the Caching concept in the Github
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3
      - name: Create a file
        run: echo $(date)>Demofile.txt
      - name: Printing the Github workspace
        run: echo "${{github.workspace}}"
      - name: Printing the list of files
        run: ls ${{github.workspace}}
        
      - name: Caching Demofile.txt
        id: demo-cache-id
        uses: actions/cache@v3
        with:
          path: Demofile.txt
          key: ${{hashfiles('cache.txt')}}
      - name: Printe content of Demofile
        run: cat Demofile.txt

      - name: Cache found
        if: ${{steps.demo-cache-id.outputs.cache-hit == 'true'}}
        run: echo "cache found"

      - name: Cache not found
        if: ${{steps.demo-cache-id.outputs.cache-hit != 'true'}}
        run: echo cache not found
     
        
        
