name: A sample Dot net Framework solution build
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ExceptionHandling.yml
      - ExceptionHandlingDemo

jobs:
  ExceptionHandling_build:
    name: Build the ExceptionHadling Solution
    runs-on: windows-latest
    
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      - name: Setup the Msbuild
        uses: microsoft/setup-msbuild@v2
      - name: List all the files
        run: dir
      - name: Build the ExceptionHandling Solution
        run: msbuild ExceptionHandlingDemo/ExceptionHandlingDemo.sln -t:rebuild -property:Configuration=Release
      - name: List the files
        run: dir
      - name: Display Github RunnerName
        run: echo "${{runner.name}}"
      - name: Upload BuildArtifacts
        uses: actions/upload-artifact@v3
        with:
          name: exceptionhandling-exe
          path: ExceptionHandlingDemo/bin/Release/ExceptionHandlingDemo.exe

  Running_build_Output:
    name: Running the ExceptionHandlingDemo executable
    runs-on: windows-latest
    needs: ExceptionHandling_build
    steps:
      - name: Display the Github Runner name
        run: echo "${{runner.name}}"
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: exceptionhandling-exe
      - name: List the files in the workspace of Github running
        run:  |
          echo " Listing the content of the directory"
          dir ./exceptionhandling-exe/
          ls ${{github.workspace}}
      - name: Display workspace information 
        run: echo "${{github.workspace}}"
      - name: Execute the excpetionhandlingdemo
        run: ./exceptionhandling-exe/ExceptionHandlingDemo.exe 10 5
        
    

    
    
