name: A sample Dot net Framework solution build
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ExceptionHandling.yml
      - .ExceptionHandlingDemo

jobs:
  ExceptionHandling_build:
    name: Build the ExceptionHadling Solution
    runs-on: windows-latest
    
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      - name: Build the ExceptionHandling Solution
        run: msbuild ExceptionHandlingDemo.sln -t:rebuild -property:Configuration=Release
    

    
    
