name: To understand the subject of Inputs
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'Test'
jobs:
  inputs:
    name: Inputs in the workflow files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Greetings
        run: echo " ${{inputs.name}}"
