name: Push to aws Lambda function
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/LambdaDeployment.yml
jobs:
  Lambda-deployment:
   name: Push to Lambda deployment
   runs-on: ubuntu-latest

   steps:
     - name: Checkout the code
       run: actions/checkout@v3
     - name: List the files in the directory
       run: ls -l

       
