name: Push to aws Lambda function
run-name: ${{github.repository}} - ${{github.workflow}} - ${{github.run_number}} - ${{github.run_id}} _ ${{github.run_attmpt}}
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/LambdaDeployment.yml
jobs:
  Listthe-filesfirst:
   name: Push to Lambda deployment
   runs-on: ubuntu-latest

   steps:
     - name: Checkout the code
       uses: actions/checkout@v3
     - name: List the files in the directory
       run: ls -l

  ZIPthefiles:
    name: Zip the files
    runs-on: ubuntu-latest
    steps:
      - name: Zipping the files
        run: zip -r File.zip File3.txt
 

 

       
