name: A Sample Workflow
on: push
jobs:
  build-job:
    name: Welcome to the sample workflow in Github
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the code
       uses: actions/checkout@v2
     
     - name: Print Hello-World
       shell: bash
       run: echo "Hello World"

     - name: Print the content of the files presented in teh repository
       run: cat File3.txt

     - name: Print the content of the all the files
       run: |
        cat file2.txt
        cat File3.txt
  
