name: Build and Deploy - RunID
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/RunIDUnderstand.yml

jobs:
  build:
    name: Build and Create Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: List the files in the directory
        run: |
          echo "ls ${{github.repository}}"
          ls -l
          ls -l ./MyApp

      - name: Build ExceptionHandlingDemo
        run: dotnet build MyApp/MyApp.sln --configuration Release

      - name: Create an Artifact
        run: dotnet publish -c Release -o ./artifacts

      - name: List the files in the workfing directory
        run: ${{github.repository}}
