name: Build and Deploy - RunID
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/RunIDUnderstand.yml

jobs:
  build:
    name: Build and Create Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Install Python and NodeJs
        uses: srinivasthoudoju/Compositeactions@main

      - name: Check the Python version
        run: python --version

      - name: Check the node version
        run: node --version

      - name: List the files in the directory
        run: |
          echo "ls ${{github.repository}}"
          ls -l
          ls -l ./MyApp

      - name: Build MyApp
        run: dotnet build MyApp/MyApp.sln --configuration Release

      - name: Run the MyApp Application
        run: dotnet run --project ./MyApp

      - name: Create an Artifact
        run: dotnet publish MyApp/MyApp.csproj -c Release -o ./artifacts

      - name: List of files in the Artifact location
        run: ls -l ./artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-artifact-${{github.run_id}}
          path: ./artifacts

      - name: Get RunId
        run: echo "This pipeline RunID is:${{github.run_id}}"

  deploy:
    name: deploy MyApp
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp-artifact-${{github.run_id}}

      - name: Deploy to environment
        run: | 
          echo "Deploying artifact for RunID: ${{github.run_id}}"
        
        

      
