name: 3rd Demo workflow
run-name: ${{github.repository}} - ${{github.workflow}} - ${{github.run_number}} - ${{github.run_attempt}
on:
  workflow_dispatch
env:
  Day_Of_Week: Wednesday
jobs:
  build-job:
    name: Build And Analyze job
    runs-on: ubuntu-latest
    env:
      Greeting: Hi! How are you
      City: Hyderabad
    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3
        
      - name: Printing the environment variables
        run: |
          echo "Value of DayOfweek is: ${{ env.Day_Of_Week }}"
          echo "Value of Greeting is: ${{ env.Greeting }}"
          echo "Value of City is: ${{ env.City }}"

      - name: "Say Hi It's Wednesday"
        if: ${{ env.Day_Of_Week == 'Wednesday' }}
        run: |
          echo "${{env.Greeting}} ${{env.FirstName}}. Today is ${{env.Day_Of_Week}}"
        env:
          FirstName: Srinivas
         
        
        
