name: A Demo variable workflow
on:
  push:
    branches:
      - main
env:
  Day_Of_Week: Monday
jobs:
  build-job:
    name: A sample demo variable 
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Printing the variable values
        run: |
          echo "Value of day of week is: {{ env.Day_Of_Week }}"
          echo "Value of Greeting is: $Greeting"
          echo "Value of Repo variable is: {{ vars.REPOVARIABLE }}"

      - name: "Say Hello! Its Monday"
        if: ${{ env.Day_Of_Week == 'Monday'}}
        run: echo "${{env.Greeting}} ${{env.FirstName }}. Today is ${{env.Day_Of_Week}}"
        env:
          FirstName: Srinivas
        
        
        
    
  
